### ISSUE TITLE
Support empty "Last week" section?

### ISSUE THREAD

**Issue by jmid** [tarides/okra#104]
For an engineer report `okra lint` doesn't currently support an empty `# Last week` section:

```bash
$ okra lint -e /tmp/person.md 
[ERROR(S)]: /tmp/person.md

Missing includes section: LAST WEEK
```
resulting from this example report:
```
# Last Week

# Other

- @person (1 day)
- a meeting
- a non-project task

## Days off

- @person (4 days)
```
I realize this is a corner-case though.

**Comment by MagnusS** [comment]
To satisfy the linker this could also be reported as 

# Last week

**Comment by gpetiot** [comment]
I don't think this is relevant anymore, I'm closing this issue.
