### ISSUE TITLE
Granularity <0.5 days is silently rounded down

### ISSUE THREAD

**Issue by jmid** [tarides/okra#111]
Consider the following weekly report:
```
$ cat /tmp/report.md 
# Last Week

- Foo-foo foo (Foo05)
  - @NameName (0.25 days)
  - Foo the foo

- Bar barbar bar (Bar07)
  - @NameName (2.75 days)
  - Barred the barbar bar
```

and compare with the days resulting from `okra cat`:
```
$ okra cat -e /tmp/report.md 
# Last Week

- Bar barbar bar (Bar07)
  - @NameName (2.5 days)
  - Barred the barbar bar

- Foo-foo foo (Foo05)
  - @NameName (0 days)
  - Foo the foo
```

Because of the rounding, the sum changes silently from 3 days to 2.5 days without notifying the user.
A warning or an error would be acceptable I think.

This is running git+https://github.com/MagnusS/okra.git#release as described in the README.

Related issues and PRs: #30 #52 #89

**Comment by gpetiot** [comment]
Made obsolete by #177 (we now fail during the parsing)
