### ISSUE TITLE
Okra cat engineer includes extra headers.

### ISSUE THREAD

**Issue by tmcgilchrist** [tarides/okra#113]
Using okra cat to compile weekly engineer reports sometimes includes stray headings from the cat'ed reports. `cat engineer-1.md engineer-2.md engineer-3.md > okra cat --engineer team-report.md`

engineer-1.md
``` 
engineer-2 week 27: 2022/07/04 -- 2022/07/10

# Projects
- Project 1 (OKR-123)
  - @engineer-1 (1 day)
```
the header `engineer-2 week 27: 2022/07/04 -- 2022/07/10` will end up in the `team-report.md`.

**Comment by gpetiot** [comment]
This is an old issue, and I couldn't reproduce the issue on recent reports.
I'm closing but feel free to re-open if you experienced the problem recently.
