### ISSUE TITLE
Release okra, possibly to a tarides-private OPAM repository 

### ISSUE THREAD

**Issue by kayceesrk** [tarides/okra#144]
Currently, okra users pin a branch. This workflow is fragile since any changes to the main branch may cause the tool to fail. Consider tagging and releasing okra versions. Any changes to the timesheets and reporting should be rolled out along with the changes in the Okra version.

**Comment by gpetiot** [comment]
@kc @samoht @kit-ty-kate I've set up https://github.com/tarides/opam-repository, but do we have a server where I can upload the tarball containing the index (generated with `opam admin index`) ? It feels wrong to upload it on a github repo (also no one is doing that).

**Comment by kit-ty-kate** [comment]
@gpetiot why do you want a tarball repository? Why not using the git repository as is?
```
opam repository add tarides git+https://github.com/tarides/opam-repository
```

**Comment by gpetiot** [comment]
I was just following the doc here: https://opam.ocaml.org/doc/Manual.html#Repositories but if we don't need that it's even better, thanks!

**Comment by kit-ty-kate** [comment]
the reason why it fails is that there is no way to distinguish between an http endpoint and a git endpoint from the url alone.

You either need to pass `--kind git` or prefix the url with `git+` or have a url that ends with `.git`. The command shown above work fine for example: https://github.com/tarides/okra/issues/144#issuecomment-1959563561

**Comment by gpetiot** [comment]
Thanks again Kate!

okra.0.1 has been released (https://github.com/tarides/opam-repository/pull/4), so I'm closing this issue.

**Comment by kit-ty-kate** [comment]
Note that it would be best to have the repository being public so that users do not have to type their github password everytime they do `opam update`

**Comment by kayceesrk** [comment]
I’m ok with making the repo public. By Tarides private, I only meant that we need not release the tool on opam as it seems to serve a very specific purpose for Tarides.

**Comment by samoht** [comment]
https://github.com/tarides/opam-repository is now public
