### ISSUE TITLE
okra team lint internal error without specifying a repo

### ISSUE THREAD

**Issue by jmid** [tarides/okra#146]
I learned about `okra team lint` today! 
It works great with, e.g., `okra team lint --okr-db=data/db.csv -C . -W 01-05` after defining a team in my `~/.config/okra/conf.yaml` :tada: 

However, before I got it running I forgot to pass `-C`, in which case it fails without a message as to why:
```
~/tarides/admin$ okra team lint --okr-db=data/db.csv -W 01-05
okra: internal error, uncaught exception:
      Invalid_argument("option is None")
      
```

This made it harder to realize my mistake. With a backtrace enabled I eventually realized that the -C option is required when using `okra team` subcommands:
```
~/tarides/admin$ OCAMLRUNPARAM=b okra team lint --okr-db=data/db.csv -W 01-05
okra: internal error, uncaught exception:
      Invalid_argument("option is None")
      Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
      Called from Dune__exe__Team.lint in file "bin/team.ml", line 20, characters 13-26
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```

It would be nice to have the tool fail with a more descriptive error message.
One could also let $PWD be the default if no -C, --repo-dir=DIR or $OKRA_REPO is set.

**Comment by gpetiot** [comment]
I've opened #152 to fix this issue, let me know if the error message is enough or if anything should be changed.
