### ISSUE TITLE
Report on objectives and not WIs

### ISSUE THREAD

**Issue by kayceesrk** [tarides/okra#167]
Given the [proposal process](https://www.notion.so/taridescompany/Proposal-Process-db717299c7944eb481811110a40e2316), all the work is planned and executed at the granularity of objectives. Currently, the reports are collected at the work item (WI) level. Note that each WI comes under an Objective. Tarides' current Team Objectives and WIs are maintained in the Github project:

* Objectives (Team): https://github.com/orgs/tarides/projects/27
* Work Items (Team): https://github.com/orgs/tarides/projects/25

We would like to move towards weekly reporting under objectives rather than WIs. This has a number of advantages:

1. Engineer weekly reports and reports for the clients operate at the same granularity.
2. Fewer buckets to report under (number of objectives << number of WIs). Makes misreporting less likely.

That said TLs have expressed that reporting on WIs is useful to produce reports other than client reports, where granularity is useful. Such as newsletters.

For this to happen, 

1. `okra` needs to be updated such that it can accept reports at the objective level.
2. Engineers need a quick way to know which objective a WI comes under. Can the `okra` tool do this?
3. Can the weeklies be made against objectives with an optional WI field? Both the objective and WI need to be checked for correctness -- that they are open, that the WI does indeed come under the objective.

CC @GemmaG @jmid who have expressed opinions about this.

**Comment by shindere** [comment]
If we report by objectives, what would be the use for maintaining two
sets of numbers (objectives and work items)?

To be more precise, assumingthere would actually be value in
maintainingtwo sets of identifiers, are we sure this value compensates
the complexity that we can experiment in having to deal with two
different sorts of things?

**Comment by kayceesrk** [comment]
> If we report by objectives, what would be the use for maintaining two
sets of numbers (objectives and work items)?

My proposal is that we wouldn't maintain the work items explicitly at the company-level when we start reporting on objectives. The work items would be team-internal information, if the team wants to maintain it (the WIs will be in the proposal). It was mentioned in the TL meeting that some TLs preferred maintaining the separation because, naturally, the project had a separation, which was useful for producing various reports. 

Note that we already have two different sets of identifiers. Every work item in https://github.com/orgs/tarides/projects/25/views/1 appears under a unique objective in https://github.com/orgs/tarides/projects/27. 

See for example, the work items in https://github.com/orgs/tarides/projects/27/views/1?pane=issue&itemId=32599165. Instead of reporting on the work items: tarides/workitems#84, tarides/workitems#1068, tarides/workitems#1069 and tarides/workitems#1070, the engineers would report directly under tarides/objectives#58. Because the TLs suggested that they want the WI number, my suggestion (3) in the original comment is to include an optional WI and check that (a) WI actually appears under the objective and (b) WI and objectives are active.
