### ISSUE TITLE
Make sure work items are active

### ISSUE THREAD

**Issue by shindere** [tarides/okra#170]
Currently, nothing prevents a weekly from referring to a no longer
active work item. Should linting perhaps make sure the mentionned issues
are stillopened?

**Comment by shindere** [comment]
KC Sivaramakrishnan (2024/03/04 08:39 -0800):
> https://github.com/tarides/okra/issues/109 is also referring to the
> same thing. It may be useful to close the old issue in favour of this
> new one. @gpetiot.

Yeah apologies, I saw only later.

Perhaps this one is easier to address because smaller and does not
depend on whether we log by WI or objective...

**Comment by gpetiot** [comment]
This is implemented in #228.
@shindere @rikusilvola would you like to give it a try before I merge? There are some tests, but feedback is welcome.
