### ISSUE TITLE
Default verbosity of activity

### ISSUE THREAD

**Issue by jmid** [tarides/okra#191]
Thanks to the efforts of @gpetiot in https://github.com/tarides/get-activity/pull/39 I now have `okra gen` working again with version 0.3.0! :tada: 

I noticed that it's `# Activity` reports are more verbose on `okra.0.3.0` compared to `okra.0.2.0`.
As several engineers construct weeklies by cut-and-pasting the  `# Activity` lines to the right WI,
I'm concerned this will inflate the resulting weeklies needlessly.

Below follows a concrete example of the activity output running `okra gen --week 13`.

Personally I find it excessive to have, e.g., 3 lines - one for each comment on an issue!
As a team lead, I do not enjoy the prospect of having to clean-up such noise when summarizing and aggregating weeklies. 
As such, I think it would be worth discussing what a reasonable verbosity level would be.
I would personally much prefer the `okra.0.2.0` verbosity level.

With `okra.0.3.0` + `get-activity.2.0.1`
```
# Activity (move these items to last week)

  - PR: [WIP] Add debug bytecode [ocaml-multicore/multicoretests#448](https://github.com/ocaml-multicore/multicoretests/pull/448)
  - PR: Move 520-workflows on GitHub actions to 5.2.0~beta1 [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
  - Merged "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
  - Commented on PR "Revert temporary acceptance in STM Out_channel test" [ocaml-multicore/multicoretests#441](https://github.com/ocaml-multicore/multicoretests/pull/441#issuecomment-2024987545)
  - Commented on PR "Revert temporary acceptance in STM Out_channel test" [ocaml-multicore/multicoretests#441](https://github.com/ocaml-multicore/multicoretests/pull/441#issuecomment-2024011014)
  - Commented on PR "Revert temporary acceptance in STM Out_channel test" [ocaml-multicore/multicoretests#441](https://github.com/ocaml-multicore/multicoretests/pull/441#issuecomment-2023323675)
  - Commented on PR "CI: Add native and bytecode workflows using MSVC" [ocaml-multicore/multicoretests#399](https://github.com/ocaml-multicore/multicoretests/pull/399#issuecomment-2023241619)
  - Commented on issue "[ocaml5-issue] Output to closed Out_channel fails to raise Sys_error" [ocaml-multicore/multicoretests#432](https://github.com/ocaml-multicore/multicoretests/issues/432#issuecomment-2022635988)
  - Commented on PR "CI: Add native and bytecode workflows using MSVC" [ocaml-multicore/multicoretests#399](https://github.com/ocaml-multicore/multicoretests/pull/399#issuecomment-2022629618)
  - Commented on PR "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445#issuecomment-2022544115)
  - Commented on PR "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445#issuecomment-2020932011)
  - Commented on issue "[ocaml5-issue] Deadlock in Dynlink test on Cygwin+MinGW" [ocaml-multicore/multicoretests#307](https://github.com/ocaml-multicore/multicoretests/issues/307#issuecomment-2020879349)
  - Commented on issue "[ocaml5-issue] Deadlock in Dynlink test on Cygwin+MinGW" [ocaml-multicore/multicoretests#307](https://github.com/ocaml-multicore/multicoretests/issues/307#issuecomment-2020592086)
  - Issue: [ocaml5-issue] Segfault in `STM Domain.DLS test sequential` on 32-bit trunk [ocaml-multicore/multicoretests#446](https://github.com/ocaml-multicore/multicoretests/issues/446)
  - Issue: [ocaml5-issue] Assertion failure during `STM Out_channel test parallel` [ocaml-multicore/multicoretests#447](https://github.com/ocaml-multicore/multicoretests/issues/447)
  - Commented on issue "[TSan] Random failure of `tests/parallel/domain_dls.ml`" [ocaml/ocaml#13059](https://github.com/ocaml/ocaml/issues/13059#issuecomment-2028022191)
  - Commented on PR "conf-efl: clean-up logic and fix Debian and Ubuntu package names" [ocaml/opam-repository#25549](https://github.com/ocaml/opam-repository/pull/25549#issuecomment-2018989993)
  - Commented on PR "conf-glpk: add FreeBSD support" [ocaml/opam-repository#25555](https://github.com/ocaml/opam-repository/pull/25555#issuecomment-2018982318)
  - PR: Add ocaml-variants.5.2.0~beta1+options+win [shym/custom-opam-repository#10](https://github.com/shym/custom-opam-repository/pull/10)
  - Commented on issue "get-activity.1.0.1 broken?" [tarides/get-activity#32](https://github.com/tarides/get-activity/issues/32#issuecomment-2020339914)
  - Commented on issue "get-activity.1.0.1 broken?" [tarides/get-activity#32](https://github.com/tarides/get-activity/issues/32#issuecomment-2018770510)
  - Issue: get-activity.1.0.1 broken? [tarides/get-activity#32](https://github.com/tarides/get-activity/issues/32)
```

With `okra.0.2.1` + `get-activity.0.2.0`
```
# Activity (move these items to last week)

  - PR: Move 520-workflows on GitHub actions to 5.2.0~beta1 [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
  - PR: [WIP] Add debug bytecode [ocaml-multicore/multicoretests#448](https://github.com/ocaml-multicore/multicoretests/pull/448)
  - Issue: [ocaml5-issue] Segfault in `STM Domain.DLS test sequential` on 32-bit trunk [ocaml-multicore/multicoretests#446](https://github.com/ocaml-multicore/multicoretests/issues/446)
  - Issue: [ocaml5-issue] Assertion failure during `STM Out_channel test parallel` [ocaml-multicore/multicoretests#447](https://github.com/ocaml-multicore/multicoretests/issues/447)
  - PR: Add ocaml-variants.5.2.0~beta1+options+win [shym/custom-opam-repository#10](https://github.com/shym/custom-opam-repository/pull/10)
  - Issue: get-activity.1.0.1 broken? [tarides/get-activity#32](https://github.com/tarides/get-activity/issues/32)
```

**Comment by jmid** [comment]
The above example illustrates adding 3 new event types to the activity report:
- PR comments
- Issue comments
- Merge events

For the purposes of our weeklies, do we want/need to enable all of them by default?

**Comment by shindere** [comment]
I'm the one who asked for a more verbose report on activities.

More specifically, what I did ask for was a more _complete_ report,
covering all the PRs and issues, even those where we just commented and
not only (for PRs) those for which we did reviews.

However? I did say that what I was lookking for was one entry per
PR/issue and not one per comment, independently of thenumber of linesof
those entries.

What I wanted was to save theeffort to keep track of the PRs and issues
I did participate to.

**Comment by jmid** [comment]
Thanks Seb. Aiming for completeness makes sense to me as PRs may stretch over several weeks.
In that case we should group issues+PRs according to their id and only report one line for each:
```
PR, commented, merged: Move 520-workflows on GitHub actions to 5.2.0~beta1 [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
```

One could go a step further and limit the report to the most significant of such events when the same engineer initiates them. For example with an order: "PR > merged > commented" the above would just output:
```
PR: Move 520-workflows on GitHub actions to 5.2.0~beta1 [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
```
That way, commenting is still included (for other people's PRs+issues or for our own older ones), so we preserve completeness, while reducing verbosity.


Note: I suspect there is still a bug in the completeness of the new events.
This old PR I also merged last week: https://github.com/ocaml-multicore/multicoretests/pull/441
but the `Merged` event is not included in the above activity report.

**Comment by gpetiot** [comment]
I can definitely look into grouping related entries together.

**Comment by kayceesrk** [comment]
> As several engineers construct weeklies by cut-and-pasting the # Activity lines to the right WI, I'm concerned this will inflate the resulting weeklies needlessly.

> As a team lead, I do not enjoy the prospect of having to clean-up such noise when summarizing and aggregating weeklies.

I like the fact that we can produce the activity which includes the comments made as well. As a developer, I often spend a lot of time thinking and responding to comments, often more than making PRs and opening issues. It is great that get-activity can produce this information as a starting point for constructing weeklies. 

That said, I agree that copy-pasting comment lines directly into the weekly would be excessive. With the "consumer of weekly" hat on, what I would like from the engineers is the summary of the work, and not just links to comments made. 

Perhaps we can go with having the default get-activity to produce only opened issues and PRs, and an `--include-comments` (or similar) option that produces activity that includes comments. One can use the former to "copy-paste" them into the weekly, and the latter to use as the starting point of writing a contextualised summary of the work done.

**Comment by jmid** [comment]
> I can definitely look into grouping related entries together.

Grouping by issue/PR would be welcome! 
For the example week above, related PR/issue events are spread apart in the output: 
```
  - PR: Move 520-workflows on GitHub actions to 5.2.0~beta1 [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
  - Commented on PR "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445#issuecomment-2020932011)
  - Commented on PR "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445#issuecomment-2022544115)
  - Merged "Move 520-workflows on GitHub actions to 5.2.0~beta1" [ocaml-multicore/multicoretests#445](https://github.com/ocaml-multicore/multicoretests/pull/445)
```

**Comment by jmid** [comment]
> Perhaps we can go with having the default get-activity to produce only opened issues and PRs, and an `--include-comments` (or similar) option that produces activity that includes comments. [...]

Yep, I would be happy with that default!

**Comment by shindere** [comment]
Jan Midtgaard (2024/04/05 01:02 -0700):
> In that case we should group issues+PRs according to their id and only report one line for each:

Thatwas my idea yeah, that eachPR is reported only once andif that
several comments are associated to the same PR or issue they give all
collectively rise to only one entry.
That was what I suggested. :)

**Comment by shindere** [comment]
gpetiot (2024/04/05 02:14 -0700):
> I can definitely look into grouping related entries together.

Thanks! I think the only things we need is the number and title of the
PR andpossibly the link. All that could be put into a linkthat opens
nicely whenyou browse the markdown document, i.e. with the mardown
syntax for links, if you see what Imean.

**Comment by gpetiot** [comment]
I have opened #208 to merge related items together, let me know what you all think.
