### ISSUE TITLE
Option to only list reports failing linting (reduced verbosity) with `okra team lint`

### ISSUE THREAD

**Issue by rikusilvola** [tarides/okra#196]
When I run `okra team lint` with a config of two dozen people for a quarter, I get two dozen times 13 lines (one per each week per engineer) plus the headers for each engineer and team.

What I really care about is whether it is something missing or if it is something not passing linting. Perhaps use grep's `-L, --files-without-match` or in this case `-L, --reports-not-passing-linting`

e.g.

```
$ okra team lint -C . -w 01-13 -L
=== The A-Team ===
    + Report week 12: Lint error at ./weekly/2024/12/mistert.md
                      In KR "@mistert (0.1 days)":
                        Invalid time entry found. Format is '- @eng1 (x days), @eng2 (y days)'
                        where x and y must be divisible by 0.5
    + Report week 13: Not found: ./weekly/2024/13/mistert.md
    + Report week 13: Not found: ./weekly/2024/13/hannibal.md
    + Report week 13: Not found: ./weekly/2024/13/howmad.md
    + Report week 5: Lint error at ./weekly/2024/05/faceman.md
                      Missing includes section: LAST WEEK
```

This would be much better than hundreds of lines listing perfectly valid reports.

PS. The first lint failure shows a bug in the error details with eng time as KR. Opening a separate bug report for that.

**Comment by gpetiot** [comment]
It sounds good to me, I think it should even be the default behavior. What do other TLs/EMs think? @sabine @pitag-ha @shindere @jmid @Sudha247 @art-w @leostera @tmattio

**Comment by jmid** [comment]
I don't have as big a team as @rikusilvola so I'm not as bothered.
Leaving no mention of any "successful lints" seems to go a bit too far IMO.
