### ISSUE TITLE
Error message for invalid time entry found is refers to time entry line as KR

### ISSUE THREAD

**Issue by rikusilvola** [tarides/okra#197]
e.g.
```
$ cat okra-197.md 
# Last week
- Leave (No KR)
  - @dummy (0.1 days)
  -
$ okra lint okra-197.md 
[ERROR(S)]: okra-197.md

In KR "@dummy (0.1 days)":
  Invalid time entry found. Format is '- @eng1 (x days), @eng2 (y days)'
  where x and y must be divisible by 0.5
```

> In KR "@dummy (0.1 days)":

Should either refer to the WI listed on the previous line ( in this case Leave (No KR) ) or simply remove the word KR.

**Comment by jmid** [comment]
Nit: #199 preserves the term `KR` in the error message.
Generally we have moved to calling these 'Work Items (WI)"

**Comment by gpetiot** [comment]
True, but the renaming has to be made everywhere in the tool, I will do everything at once in a separate PR.
