### ISSUE TITLE
Add a "Next week" section in the generated report

### ISSUE THREAD

**Issue by tmattio** [tarides/okra#24]
This is not used by the Okra, but it's a useful section to have, so it could be generated by default to encourage people to fill it

**Comment by patricoferris** [comment]
I don't mind too much either way but given we don't "lint" it I'm not sure it is worth generating by default. In my `conf.yaml` I have added it which is a nice opt-in approach: 

```yaml
footer: |
    # Next Week
    - Continue with CI, Okra and Platform Adoption
```

Any thoughts @tmattio ?
