### ISSUE TITLE
Lint can't handle objective titles with parentheses

### ISSUE THREAD

**Issue by NickBarnes** [tarides/okra#245]
[Objective #543](https://github.com/tarides/objectives/issues/543) has the title "Ensure OCaml 5 series has feature parity with OCaml 4 (Commercial)". If I include this whole title in an entry of an OKRA report:
```
- Ensure OCaml 5 series has feature parity with OCaml 4 (Commercial) (#543)
  - @NickBarnes (0.5 days)
```
then I get this error message from `okra lint --engineer --repo-dir /my/tarides/admin/repo`:
```
Error: In objective "Ensure OCaml 5 series has feature parity with OCaml 4":
       No ID found. Objectives should be in the format "This is an objective (#123)", where 123 is the objective issue ID. For objectives that don't have an ID yet, use "New KR" and for work without an objective use "No KR".
```
If I omit the parenthetical text, like this:
```
- Ensure OCaml 5 series has feature parity with OCaml 4 (#543)
  - @NickBarnes (0.5 days)
```
then I get this warning message instead:
```
okra: [WARNING] Conflicting titles:
- "Ensure OCaml 5 series has feature parity with OCaml 4"
- "Ensure OCaml 5 series has feature parity with OCaml 4 (Commercial)"
```

**Comment by shindere** [comment]
Ah, maybe just a matter of looking for the opening parenthesis starting from the right rather than from the left?

**Comment by NickBarnes** [comment]
> Ah, maybe just a matter of looking for the opening parenthesis starting from the right rather than from the left?

Indeed, I think in `KR.Heading.of_string`: possibly refactor this using `Re` instead of `String.split_on_char`?

**Comment by shindere** [comment]
Nick Barnes (2024/06/05 04:58 -0700):
> > Ah, maybe just a matter of looking for the opening parenthesis starting from the right rather than from the left?
>
> Indeed, I think in `KR.Heading.of_string`: possibly rewrite this using `Re` instead of `String.split_on_char`?

There is no `split_on_char_r` yet but `split_on_char` is not that long so we coudl define `split_on_char_r` locally.
