### ISSUE TITLE
okra lint is missing a newline

### ISSUE THREAD

**Issue by emillon** [tarides/okra#249]
Hi,

In the "Placeholder text detected" case (when "Work Item 1" is found), `okra lint -e` is missing a newline in the output.

Sample:

```
- Onboard
  - @emillon (0 days)
  - Onboarding time
  - Work Item 1
```

Output:

```
File "path.md", line 10:
```

(the content is then hidden by my shell prompt)

Thanks

**Comment by gpetiot** [comment]
Hi, I didn't manage to reproduce this error. Here is the cram test and its output, did I miss something?

```cram
  $ cat > placeholder-detected.md << EOF
  > - Onboard
  >   - @emillon (0 days)
  >   - Onboarding time
  >   - Work Item 1
  > EOF
  $ okra lint -e placeholder-detected.md
  File "placeholder-detected.md", line 4:
  Error: Placeholder text detected. Replace with actual activity.
  [1]
```

**Comment by emillon** [comment]
This is going to be tricky to test in a cram test, because cram itself is going to insert a newline. But if you write say `okra lint -e t.md 2>&1 | xxd`, you'll see that the hexdump doesn't contain a newline character at the end.
