### ISSUE TITLE
okra gen: tech talks and all hands

### ISSUE THREAD

**Issue by shindere** [tarides/okra#251]
Could okra gen's output mention the tech talks and all hands
to encourage consistent reporting of those among all of us?

**Comment by gpetiot** [comment]
For context this is related by this `get-activity` feature request: https://github.com/tarides/get-activity/issues/23 (importing activities from a calendar).
Not closing as a duplicate though, maybe it makes more sense to have this in `okra`.

Could be a good hacking days project if someone want to jump in.

**Comment by shindere** [comment]
There may be a misunderstanding happening here as what I am asking for
is actually much more low tech than what you seem to have in mind, which
is very interesting but, as you say, more involved.

I really meant to include `all hands` and `tehc talk` as pseudo-work
items under the entries where we are supposed to report them, as a
reminder that owuld be deleted most of the time.

Do I make more sense?

**Comment by gpetiot** [comment]
Oh, I misunderstood you indeed.

**Comment by jmid** [comment]
Note: because of rounding to nearest 0.5 days, unless we start having multiple ones each week, a 1h all-hands or tech-talk will have to be reported as `0 days`. As such I'm wondering whether it is worth the effort... :shrug:

**Comment by gpetiot** [comment]
Personally I report the all hands as 0.5 day so I can also account for my four 1:1 happening during the month, roughly 5 hours in total.
