### ISSUE TITLE
lint: Fail when reporting out-of-date standardized categories

### ISSUE THREAD

**Issue by gpetiot** [tarides/okra#271]
@ganeshn-gh Following up the discussion from https://github.com/tarides/admin/commit/118fa770ea1cad4059a018f86f24b1dcda5e726b#comments

okra 1.0.0 was announced June 6, 2024, it introduced the following standardized categories:
- Community
- Hack
- Learning
- Leave
- Management
- Meet
- Onboard

So these categories were accepted from week 24.

okra 2.1.0 was announced June 19, 2024, it introduced the following standardized categories:
- Off
- Hack
- Misc

These categories were accepted from week 26.

Instead of splitting the validity check of these categories like this:
- before week 24: nothing
- week 24-25: 1.0.0 categories are valid
- week 26 and later: 2.1.0 categories are valid

Could we just pretend that the ones released in 1.0.0 don't exist, rewrite the reports submitted during weeks 24-25 using the 2.1.0 categories. So we would only check if the categories used are Off, Hack, Misc, no matter the week. This way we would synchronize with the date (week 24) where we expect the users to use objectives and fail on WIs.

What do you think? @ganeshn-gh

**Comment by ganeshn-gh** [comment]
> Could we just pretend that the ones released in 1.0.0 don't exist, rewrite the reports submitted during weeks 24-25 using the 2.1.0 categories. So we would only check if the categories used are Off, Hack, Misc, no matter the week. This way we would synchronize with the date (week 24) where we expect the users to use objectives and fail on WIs.
> 
> What do you think? @ganeshn-gh
>
Yeah, it sounds good to me.

**Comment by ganeshn-gh** [comment]
@gpetiot Can you confirm if [this] (https://github.com/tarides/admin/commit/9cbb688fde482088fb634d6af65c68dac2bce56f) weekly would fail the linter? 
As of now, it gives a warning for the WIs. After a PR is merged for this issue, I hope the linter will emit an error. 
I would like to understand if it fails only the categories released on June 6th, 2024, or the work items.

**Comment by gpetiot** [comment]
Yes the linting should fail.
For the workitems, the change is already merged: https://github.com/tarides/okra/pull/270
