### ISSUE TITLE
Update the outdated Caretaker

### ISSUE THREAD

**Issue by ganeshn-gh** [tarides/okra#275]
Hi @gpetiot 
As discussed on updating the caretaker, I would like to create a new issue to get a better csv output.
https://github.com/tarides/admin/commit/118fa770ea1cad4059a018f86f24b1dcda5e726b#commitcomment-143710708

**Comment by gpetiot** [comment]
If I understand correctly, the issue you mentioned just requires caretaker to be released so it can be used by the script run on the GitHub action.
I will check nothing is blocking that then release caretaker.

**Comment by ganeshn-gh** [comment]
IIUC, you said the `csv` output is produced by an outdated version of the caretaker that also uses an outdated version of Okra. You said you'd update it, so I created an issue so that it would not be missed.

**Comment by ganeshn-gh** [comment]
> If I understand correctly, the issue you mentioned just requires caretaker to be released so it can be used by the script run on the GitHub action. I will check nothing is blocking that then release caretaker.

I'm sorry, I couldn't understand the process of the script running on the GitHub action. What would be the outcome of this?

**Comment by gpetiot** [comment]
caretaker have been released and the script generating https://github.com/tarides/admin/blob/main/data/2024-all.csv has been updated. I'm closing this issue.
