### ISSUE TITLE
Caretaker error in the csv output

### ISSUE THREAD

**Issue by ganeshn-gh** [tarides/okra#276]
If you see @EmileTrotignon's [weekly](https://github.com/tarides/admin/blob/main/weekly/2024/23/EmileTrotignon.md), he has recorded data for five days. But the caretaker's [output](https://docs.google.com/spreadsheets/d/1038sq4pvvsx1EW6WMMwCXbTW1GO1gWPMcXzmhyj71iE/edit?gid=0#gid=0) has only 4.5 days. 

<img width="703" alt="Emile - week 23" src="https://github.com/tarides/okra/assets/95270674/57742b45-eb94-48f8-a34b-cd99cf5a31b2">

I understand he has used the `Meetings` objective, which is not the correct objective, but how does the caretaker extract the objectives which are incorrect as well, like the one below,

<img width="711" alt="workitem#1167" src="https://github.com/tarides/okra/assets/95270674/db105e29-cc8e-4669-88cc-d5696aa8b517">

**Comment by gpetiot** [comment]
This is now what is in the csv file:
```csv
"#1074","2024","06","23","EmileTrotignon","0.5"
"#1082","2024","06","23","EmileTrotignon","0.5"
"#67","2024","06","23","EmileTrotignon","4.0"
```

```csv
"#715","2024","06","26","emillon","0.5"
"#723","2024","06","26","emillon","1.5"
"#735","2024","06","26","emillon","1.0"
"Hack","2024","06","26","emillon","1.0"
"Misc","2024","06","26","emillon","1.0"
```

So I consider the issue fixed, I'm closing this issue.
