### ISSUE TITLE
Allow hourly-level granularity

### ISSUE THREAD

**Issue by sadiqj** [tarides/okra#280]
Given that:

- Weeklies provide the raw data used to bill customers (internally or externally) for work carried out
- Many projects can involve small amounts of time (<0.5 days a week) over long periods of time
- Rounding down at 0.5 day granularity prevents Tarides from billing for this time
- Rounding up at 0.5 day granularity bills customers for time not actually worked

Okra should support up to hour-level granularity. This could be implemented as support for 0.125 day increments.

**Comment by gpetiot** [comment]
This is not the case, see the answer of @samoht here: https://github.com/tarides/okra/pull/205#issuecomment-2048213893

**Comment by kayceesrk** [comment]
Given that we have linting support that checks that updates sum up to 5 days, it is ok to support this feature now. I checked offline with @GemmaG that reporting in 0.125 days granularity is fine as long as we can confirm that the reports sum up to 5 days a week. 

For a start, to avoid the problem of working hours being different between countries, I would just reduce the granularity from 0.5 to 0.125. Assuming an 8-hour working day, 0.125 days will be an hour. We can implement conversions later.

**Comment by gpetiot** [comment]
In https://github.com/tarides/okra/pull/205#issuecomment-2048213893 I implemented the conversion, assuming 1 day is always equal to 8h. Should I reopen the PR? Surely reporting 1h is more user friendly than 0.125 days

**Comment by kayceesrk** [comment]
If I report 2 hrs of work for the week and the rest of the time as off, can I write time off as 4.75 hours? We should make sure the current workflow remains unaffected.

**Comment by sadiqj** [comment]
Thank you!
