### ISSUE TITLE
Permit "Days off" as a special KR?

### ISSUE THREAD

**Issue by dra27** [tarides/okra#33]
It's useful for that to appear to in counts (it's in the original template);

```
- Days off
  - @dra27 (1 day)
```

**Comment by emillon** [comment]
I think that at some point there was an `HRxx` code for this?

**Comment by emillon** [comment]
even with a proper code it needs to have a description attached so it's not great:

```
- Off (HR0)
  - @emillon (1 day)
  - off
```

Since it's to be ignored by the rest of the process, we can also put it in a different section:

```
# Off

1 day

# Last week

...
```

**Comment by dra27** [comment]
For now I adopted @patricoferris's style from the summer which was to include it as a lone sentence at the end of `Projects` (Patrick puts days worked; I tend to put days off as I often [choose to] clock hours at the weekend, so days worked makes less sense!)

**Comment by MagnusS** [comment]
Time off is not really tracked with the KRs -- it's probably better to add it in an ignored section if you want to include it in the weekly, e.g. in `# Projects` or add a `# Notes` section. Then you can look it up if necessary, but it won't be included in the upstream report.

**Comment by MagnusS** [comment]
Perhaps we could add this in a different way, e.g. a summary per engineer when you run the linter to look for obvious errors? It's fine if the numbers don't add up to 5 (or days worked) every week, not everything maps to a KR :)

**Comment by gpetiot** [comment]
Subsumed by #145
