### ISSUE TITLE
lint: does not catch when engineer report output no KRs

### ISSUE THREAD

**Issue by emillon** [tarides/okra#49]
Hi,

The following engineer report passes lint but will output no KRs:

```
## OKR updates

- Some work (Work1)
  - @e (1 day)
  - did some work
```

2 things to note here:
- when using `cat -e`, everything is silently dropped (because there's no "Last week" section). I suggest that when `--include-krs` is passed, a check is added that it matches something
- when fixing that to `## Last week`, the error "The input should contain at least one title (starting with #)" fires. I'm under the impression that it should fire even if the section is somehow ignored

Thanks!

**Comment by emillon** [comment]
something similar happens when there's no title at all.

**Comment by gpetiot** [comment]
Nowadays, this returns `Missing includes section: LAST WEEK`, so I consider this fixed and closing the issue.
