### ISSUE TITLE
Possible `okra diff` to view work reported to your own KRs in other aggregates

### ISSUE THREAD

**Issue by dra27** [tarides/okra#88]
From discussion this morning in the reduced TLs meeting! Some work for OKRs not "owned" by a TL may be reported in their KR instead of bounced to the KR's owner (e.g. opam-repository work in Plat125; talks in Com17). It'd be useful to be able to see what's in the team-weeklies, issuing something like:

```
okra diff okr-updates/team-weeklies/2021/44 dra27.md
```
which would take all the OKRs reported in `okr-updates/team-weeklies/2021/44/dra27.md` and then display any reports for those KRs present in other files in `okr-updates/team-weeklies/2021/44` or, possibly better, ignore `dra27.md` entirely but display reports from any other file where the KR is _owned_ by dra27.

**Comment by gpetiot** [comment]
This issue is pretty old, is it still relevant today, do you still have the need for this feature?

**Comment by dra27** [comment]
I not a TL any more, so someone else wants to own it 🙂 That said, given that team aggregates aren't done in the same way these days, this might now be dealt with elsewhere?

**Comment by gpetiot** [comment]
Since we're about to use the objectives instead of the WIs I'm closing this issue, it won't be as relevant as in the past.
