### ISSUE TITLE
Add ability to report "< 0.5 days"

### ISSUE THREAD

**Issue by dra27** [tarides/okra#89]
There are occasions where a piece of work or a note is valuable in a report but it very clearly did not take 0.5 days of someone's time. I have been seeing (and also myself adding) occasional items like this with `@dra27 (0 days)` but this looks a little silly and it's not the most encouraging to have engineers write 🙂

Perhaps instead we can in future reject `0 days` in `okra lint` and instead permit `< 0.5 days`? When adding `< 0.5 days` can be treated as zero, we just never display `0`.

**Comment by gpetiot** [comment]
Closing this one in favor of #111
